### ISSUE TITLE
Broken links on https://joss.theoj.org/papers/active

### ISSUE THREAD

**Issue by rweigel** [openjournals/joss#558]
I came across a broken link to [a paper](https://joss.theoj.org/papers/310a0fa5052bdaf3d398bf1fefa32b6ea) in my RSS feed.

It appears that all of the links on https://joss.theoj.org/papers/active are not working.

**Comment by kyleniemeyer** [comment]
Yeah, I believe the links on that page should lead to the review thread.

**Comment by arfon** [comment]
Thanks @rweigel. This should be fixed now. Can you verify?

**Comment by rweigel** [comment]
@arfon - Still broken.

Also, links at https://joss.theoj.org/papers are broken (checked first two).

**Comment by rweigel** [comment]
May want to use something like https://github.com/endymion/link-checker as a post-commit hook.

**Comment by arfon** [comment]
OK, thanks for the quick response.

The issue is caused by the fact that we're trying to hide from general readers papers that are submitted but haven't been through the 'pre-flight' check by an editor yet.

Thanks for helping me debug this - could you check again now? If you find a link that doesn't work, please post the broken URL here.

**Comment by rweigel** [comment]
Thanks. It seems fixed now. 

For completeness, I ran

https://www.brokenlinkcheck.com/

and it shows a few more. I can't post the report easily into a comment, so you'll have to run it.

**Comment by arfon** [comment]
> and it shows a few more. I can't post the report easily into a comment, so you'll have to run it.

👍 thanks.
